/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'tripType' : TripType,
  'dropoffLocation' : [] | [Location],
  'fare' : number,
  'durationHours' : [] | [number],
  'pickupDate' : string,
  'pickupTime' : string,
  'pickupLocation' : Location,
}
export interface Location { 'address' : string }
export type TripType = { 'byTheHour' : null } |
  { 'pointToPoint' : null } |
  { 'airportTransfer' : null };
export interface _SERVICE {
  'calculateFare' : ActorMethod<
    [TripType, Location, [] | [Location], [] | [number]],
    number
  >,
  'createBooking' : ActorMethod<
    [
      TripType,
      Location,
      [] | [Location],
      string,
      string,
      [] | [number],
      number,
    ],
    bigint
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getBookingsBelowFare' : ActorMethod<[number], Array<Booking>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];