/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TripType = IDL.Variant({
  'byTheHour' : IDL.Null,
  'pointToPoint' : IDL.Null,
  'airportTransfer' : IDL.Null,
});
export const Location = IDL.Record({ 'address' : IDL.Text });
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'tripType' : TripType,
  'dropoffLocation' : IDL.Opt(Location),
  'fare' : IDL.Float64,
  'durationHours' : IDL.Opt(IDL.Float64),
  'pickupDate' : IDL.Text,
  'pickupTime' : IDL.Text,
  'pickupLocation' : Location,
});

export const idlService = IDL.Service({
  'calculateFare' : IDL.Func(
      [TripType, Location, IDL.Opt(Location), IDL.Opt(IDL.Float64)],
      [IDL.Float64],
      [],
    ),
  'createBooking' : IDL.Func(
      [
        TripType,
        Location,
        IDL.Opt(Location),
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingsBelowFare' : IDL.Func(
      [IDL.Float64],
      [IDL.Vec(Booking)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TripType = IDL.Variant({
    'byTheHour' : IDL.Null,
    'pointToPoint' : IDL.Null,
    'airportTransfer' : IDL.Null,
  });
  const Location = IDL.Record({ 'address' : IDL.Text });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'tripType' : TripType,
    'dropoffLocation' : IDL.Opt(Location),
    'fare' : IDL.Float64,
    'durationHours' : IDL.Opt(IDL.Float64),
    'pickupDate' : IDL.Text,
    'pickupTime' : IDL.Text,
    'pickupLocation' : Location,
  });
  
  return IDL.Service({
    'calculateFare' : IDL.Func(
        [TripType, Location, IDL.Opt(Location), IDL.Opt(IDL.Float64)],
        [IDL.Float64],
        [],
      ),
    'createBooking' : IDL.Func(
        [
          TripType,
          Location,
          IDL.Opt(Location),
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingsBelowFare' : IDL.Func(
        [IDL.Float64],
        [IDL.Vec(Booking)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };